import type { ComponentSize } from '../../types'

/**
 * 单选项值，取 Reka UI `AcceptableValue` 中可用的 `string | number` 子集
 * @en Radio value, the `string | number` subset available on Reka UI's `AcceptableValue`
 */
export type RadioValue = string | number

/**
 * 组内排列方向
 * @en In-group orientation
 */
export type RadioGroupOrientation = 'horizontal' | 'vertical'

/**
 * 阅读方向
 * @en Reading direction
 */
export type RadioGroupDirection = 'ltr' | 'rtl'

export interface RadioGroupProps {
    /**
     * 尺寸
     * @en Size
     */
    size?: ComponentSize
    /**
     * 非受控模式下的初始选中值；受控时改用 `v-model`。
     *
     * 值为 `undefined` 表示未选中。
     * @en Initial selected value in uncontrolled mode; use `v-model` instead when controlled. A value of `undefined` means nothing is selected.
     */
    defaultValue?: RadioValue
    /**
     * 是否禁用整组
     * @en Whether the whole group is disabled
     */
    disabled?: boolean
    /**
     * 是否必填（原生表单校验）
     * @en Whether it is required (native form validation)
     */
    required?: boolean
    /**
     * 表单字段名；提供后选中值随表单提交
     * @en Form field name; when provided the selected value is submitted with the form
     */
    name?: string
    /**
     * 组内排列方向，默认垂直
     * @en In-group orientation, vertical by default
     */
    orientation?: RadioGroupOrientation
    /**
     * 阅读方向
     * @en Reading direction
     */
    dir?: RadioGroupDirection
    /**
     * 键盘导航是否首尾循环
     * @en Whether keyboard navigation wraps around
     */
    loop?: boolean
    /**
     * 校验失败态，映射 aria-invalid
     * @en Validation failure state, maps to aria-invalid
     */
    invalid?: boolean
    /**
     * 根元素 id
     * @en Root element id
     */
    id?: string
    /**
     * 无可见分组标签时的可访问名，映射 aria-label
     * @en Accessible name when there is no visible group label, maps to aria-label
     */
    label?: string
}

export interface RadioButtonProps {
    /**
     * 该选项的值，需在同一组内唯一
     * @en Value of the option; must be unique within a group
     */
    value: RadioValue
    /**
     * 是否禁用该选项
     * @en Whether to disable the option
     */
    disabled?: boolean
    /**
     * 关联外部 label 的 id，缺省自动生成
     * @en Id of the associated external label; auto-generated by default
     */
    id?: string
    /**
     * 可见标签文本（也可用默认插槽自定义）
     * @en Visible label text (also customizable via the default slot)
     */
    text?: string
    /**
     * 无可见文本时的可访问名，映射 aria-label
     * @en Accessible name when there is no visible text, maps to aria-label
     */
    label?: string
}
