import './styles/index.css'

export * from './components/badge'
export * from './components/button'
export * from './components/dialog'
export * from './components/input'
export * from './components/input-number'
export * from './components/switch'
export * from './components/tag'
export * from './components/textarea'
export * from './icons'
export * from './locale'
export * from './types'
export { useTheme } from './composables/use-theme'
export type { ThemeMode, UseThemeReturn } from './composables/use-theme'
